[network]
host = "iss.moex.com"
service = "http"

[http]
userAgent = "MOEXFetcher"

[requests]
marketData = "/iss/engines/stock/markets/shares/securities.json"
candles = "/iss/engines/stock/markets/shares/securities/{ticker}/candles.json"
