name: CI – Windows MSVC Release

on:
  pull_request:
    branches: [ main, ci_test ]

jobs:
  build-release:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      # 1. Выкачиваем код
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # важно для правильного merge-base в PR

      - name: Install clang-format
        if: github.event_name == 'pull_request'   # только в PR
        run: |
          choco install llvm --version=19.1.7 -y --force --no-progress
          refreshenv   # обновляем PATH
          clang-format --version

      - name: Check code style (clang-format)
        if: github.event_name == 'pull_request'
        run: |
          # Получаем список изменённых C++ файлов в этом PR
          git fetch origin ${{ github.base_ref }} --no-tags --depth=1
          $files = git diff --name-only origin/${{ github.base_ref }} HEAD | Where-Object { $_ -match '\.(cpp|h|hpp|cxx|hxx)$' -and (Test-Path $_) }
          
          if ($files) {
          Write-Output "Проверяем стиль в изменённых файлах:"
          $files | ForEach-Object { Write-Output "  $_" }
          
          # -n = dry-run, --Werror = любая разница → ошибка CI
          clang-format -n --Werror --style=file --fallback-style=none $files
          } else {
            Write-Output "Нет изменённых C++/H файлов — проверка стиля пропущена"
          }


      # 2. Ставим Python
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # 3. Устанавливаем Conan через pip
      - name: Install Conan 2.x
        run: |
          python -m pip install --upgrade pip
          pip install conan
          conan --version

      # 4. Установка профилей conan
      - name: Deploy conan profiles
        run: |
          cd extern
          python ./conan_install.py

      # 5. Сборка extern библиотек
      - name: Install dependencies
        run: |
          cd extern
          python ./conan_msvc_script.py   
